### ISSUE TITLE
smplx import error

### ISSUE THREAD

**Issue by kuijiang94** [MPS-Net/MPS-Net_release#2]
hello, it is an interesting work. 
However, in the codes, missing the smplx file. it is very grateful to provide the complete codes.

**Comment by MPS-Net** [comment]
Hi, MPS-Net uses the SMPL model instead of the SMPLX model. 

Maybe you can convert SMPL to SMPLX by referring to the method in the following URL. https://github.com/vchoutas/smplx/blob/master/transfer_model/README.md

**Comment by kuijiang94** [comment]
thanks for your help!
